baseURL = 'https://johncraven.github.io/'
languageCode = 'en-us'
title = "John's Site"
theme = 'anatole'

[params]
title = "John Craven"
author = "John Craven"
description = "Senior Scientist @ GSK"
profilePicture = "images/profile.jpg"
contentratio = 0.75
doNotLoadAnimations = true # Animations are loaded by default

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:johndcraven@gmail.com"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/johndcraven/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/johncraven"

[[params.socialIcons]]
icon = "fab fa-goodreads"
title = "Goodreads"
url = "https://www.goodreads.com/user/show/51874054-john"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"